#
# CSE115A Rapid Review Backend
#

openapi: '3.0.3'

info:
  description: CSE115A Rapid Review Project Backend
  version: 0.1.0
  title: CSE115A Rapid Review Backend

servers:
  - url: http://localhost:3010/v0

paths:
  /set:
    get:
      description: Returns all sets as array of strings
      responses:
        200:
          description: Sets Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/setArray'
        default:
          description: Unexpected Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    put:
      description: Adds a new set to the table
      requestBody:
        description: New set as object
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/newSet'
      responses:
        201:
          description: Set added
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/keyString'
        default:
          description: Unexpected Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'            
  /set/{id}:
    put:
      description: Updates specified set with new values
      requestBody:
        description: New data as set object
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/noKeySet'
      parameters:
        - name: id
          in: path
          description: id of the set
          required: True
          schema:
            type: string
      responses:
        201:
          description: Set updated
        404:
          description: Set not found
        default:
          description: Unexpected Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error' 
    delete:
      description: Deletes specified set
      parameters:
        - name: id
          in: path
          description: id of the set
          required: True
          schema:
            type: string
      responses:
        200:
          description: Set deleted
        404:
          description: Set not found
        default:
          description: Unexpected Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error' 
          

components:
  schemas:

    setArray:
      type: array
      items:
        $ref: '#/components/schemas/Set'

    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string

    Set:
      type: object
      maxProperties: 5
      properties:
        card_num:
          type: integer
        description:
          type: string
        name:
          type: string
        owner:
          type: string
        key:
          type: string
      required:
        - card_num
        - description
        - name
        - owner
        - key
    
    noKeySet:
      type: object
      maxProperties: 4
      properties:
        card_num:
          type: integer
        description:
          type: string
        name:
          type: string
        owner:
          type: string
        key:
          type: string
      required:
        - card_num
        - description
        - name
        - owner
    
    newSet:
      type: object
      maxProperties: 3
      properties:
        description:
          type: string
        name:
          type: string
        owner:
          type: string
      required:
        - description
        - name
        - owner
        
    keyString:
      type: string