#
# CSE115A Rapid Review Backend
#

openapi: '3.0.3'

info:
  description: CSE115A Rapid Review Project Backend
  version: 0.1.0
  title: CSE115A Rapid Review Backend

servers:
  - url: http://localhost:3010/v0

paths:
    /set:
      get:
        description: Returns all sets as array of strings
        responses:
          200:
            description: Sets Response
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/stringArray'
          default:
            description: Unexpected Error
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Error'

components:
  schemas:

    stringArray:
      type: array
      items:
        type: string

    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string

