#
# CSE115A Rapid Review Backend
#

openapi: '3.0.3'

info:
  description: CSE115A Rapid Review Project Backend
  version: 0.1.0
  title: CSE115A Rapid Review Backend

servers:
  - url: http://localhost:3010/v0

paths:
  /login:
    post:
      description: Login
      requestBody:
        description: Email and password
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Credentials'
      responses:
        200:
          description: Credentials Correct
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        401:
          description: Invalid email or password
        default:
          description: Unexpected Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    Credentials:
      type: object
      maxProperties: 2
      properties:
        email:
          type: string
          format: email
        password:
          type: string
      required:
        - email
        - password

    User:
      type: object
      maxProperties: 2
      properties:
        name:
          type: string
        accessToken:
          type: string
      required:
        - name
        - accessToken

    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string

